# Generated by Django 3.1.6 on 2021-02-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ('-created',)},
        ),
    ]
